CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname text NOT NULL,
    email text NOT NULL
);

CREATE TABLE IF NOT EXISTS reserves(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    start date NOT NULL,
    title text,
    hour text,
    userid INTEGER REFERENCES users(id)
);

INSERT INTO users(fullname, email)
    VALUES('user1', 'user1@gmail.com')
